name: Build Docker Image

on: [push]

env:
  IMAGE_TAG: v1.101.0
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build_and_publish_image:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Make Imagename lowercase
      run: |
        echo "IMAGE_NAME_LC=${IMAGE_NAME,,}" >>${GITHUB_ENV}

    - name: Login to ghcr.io
      run: echo $GITHUB_TOKEN | docker login ghcr.io -u lippesola --password-stdin
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/$IMAGE_NAME_LC:$IMAGE_TAG --tag ghcr.io/$IMAGE_NAME_LC:latest
    # Push
    - name: Push the Docker image with version
      run: docker push ghcr.io/$IMAGE_NAME_LC:$IMAGE_TAG
    - name: Push the Docker image as latest
      run: docker push ghcr.io/$IMAGE_NAME_LC:latest
